# Enable service discovery routing
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# Eureka Config
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/


# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/gateway/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=2
spring.cloud.gateway.server.webflux.routes[0].filters[1]=RewritePath=/auth/v3/api-docs(?<segment>/?.*), /v3/api-docs$\{segment}

#Admin Service
spring.cloud.gateway.server.webflux.routes[1].id=admin-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/gateway/admin/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=2
spring.cloud.gateway.server.webflux.routes[1].filters[1]=RewritePath=/admin/v3/api-docs(?<segment>/?.*), /v3/api-docs$\{segment}

#Auth Service
spring.cloud.gateway.server.webflux.routes[2].id=catalog-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/gateway/catalog/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=2
spring.cloud.gateway.server.webflux.routes[2].filters[1]=RewritePath=/catalog/v3/api-docs(?<segment>/?.*), /v3/api-docs$\{segment}


#Order Service
spring.cloud.gateway.server.webflux.routes[3].id=order-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/gateway/order/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=2
spring.cloud.gateway.server.webflux.routes[3].filters[1]=RewritePath=/order/v3/api-docs(?<segment>/?.*), /v3/api-docs$\{segment}

jwt.secret=mySelfAbhishekUpadhyayAndCurrentlyIamPersuingBtechInCseFromLpu


#actuator endpoints exposed
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# Swagger Aggregation
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/gateway/auth/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Admin Service
springdoc.swagger-ui.urls[1].url=/gateway/admin/admin/v3/api-docs

springdoc.swagger-ui.urls[2].name=Catalog Service
springdoc.swagger-ui.urls[2].url=/gateway/catalog/catalog/v3/api-docs

springdoc.swagger-ui.urls[3].name=Order Service
springdoc.swagger-ui.urls[3].url=/gateway/order/order/v3/api-docs



# Zipkin endpoint (NO Docker → localhost)
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Capture all traces (dev)
management.tracing.sampling.probability=1.0



# CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
